[workspace]
resolver = "2"
members = ["locatch_query", "locatch_queryf_matchfilter", "locatch_queryr"]

[workspace.package]
authors = ["Dominic Rooney"]
edition = "2021"

[workspace.dependencies]
locatch_query = { path = "locatch_query" }
locatch_queryr = { path = "locatch_queryr" }
